FLASH_CARDS = {
    # Chapter 1 terms
    "1": {
        "accelerometer": "A device that detects the physical tilt and acceleration of the device.",
        "application (app)": "Software that allows a computer user to perform useful functions such as writing a report or calculating a budget. Commonly called an “___.”",
        "central processing unit (CPU)": "An integrated circuit (chip) that performs the calculations, or processing, for a computer. Also called a microprocessor.",
        "client": "A software component that accesses services of a network server.",
        "command-line interface (CLI)": "A user interface that consists of a character-based command line that provides only sparse amounts of information.",
        "computer": "A device that performs calculations.",
        "Chrome OS": "An operating system based on a Linux kernel with a GUI based on the Chrome web browser.",
        "cursor": "In a command-line interface (CLI), the cursor is merely a marker for the current position where what you type on the keyboard will appear. In a GUI, a graphical pointer that can have a variety of shapes you can move around by manipulating a pointing device sometimes replaces the cursor.",
        "device driver": "Software that is added to an OS to control a physical component (device). Each unique hardware device connected to a computer needs a component-specific device driver.",
        "device management": "An OS function that controls hardware devices using device drivers.",
        "directory": "A special file that can contain files as well as other directories. This term is most often used with non-GUI operating systems. When describing a directory in a GUI, the commonly used term is folder.",
        "distribution": "A bundling of the Linux kernel and software—both enhancements to the OS and applications. Applications may include word processors, spreadsheets, media players, and more.",
        "embedded OS": "An operating system stored in firmware, as in a mobile device.",
        "file management": "An operating system function that allows the operating system to read, write, and modify data and programs organized into files.",
        "file system": "The logical structure used on a storage device for storing files, as well as the code within an operating system that allows the OS to store and manage files on a storage device.",
        "firmware": "Software resident in integrated circuits.",
        "folder": "A term describing a type of file that can contain other folders as well as files—most often used with GUI operating systems. When describing a ____ in a non-GUI operating system, people most often use the term directory.",
        "formatting": "The process that writes the logical structure of a file system on a storage device.",
        "graphical user interface (GUI)": "A user interface that takes advantage of a computer's graphics capabilities to make it easier to use with graphical elements that one can manipulate to perform tasks, such as system and file management and the running of applications.",
        "input/output (I/O)": "Anything sent into a computer (input); anything coming out of a computer (output). Every keystroke you enter, all files read in, and even voice commands are input. Output can include a printed page, what you see on the screen, and even sounds.",
        "integrated circuit (IC)": "A small electronic component made up of transistors (tiny switches) and other miniaturized parts.",
        "Internet of Things (IoT)": "Devices not normally associated with computer that contain microcomputers and are connected to networks. These devices include, but are not limited to: kitchen appliances, thermostats, utility meters, components in automobiles, light bulbs, and industrial control devices.",
        "job management": "An operating system function that controls the order and time in which programs are run. For example, an operating system's print program can manage and prioritize multiple print jobs.",
        "kernel": "The main component of an operating system, which always remains in memory while a computer is running.",
        "killer app": "An application that many people need enough to purchase a computer that will run that app.",
        "Mac": "The product name for Apple's computers.",
        "memory": "The physical chips that store programs and data. There are two basic types: random-access memory (RAM) and read-only memory (ROM).",
        "memory management": "An operating system function that manages and tracks the placement of programs and data in memory. Advanced operating systems, such as Windows, Linux, and macOS use memory management to make optimal use of memory.",
        "microcomputer": "A computer built around a microprocessor.",
        "microprocessor": "An integrated circuit (chip) that performs the calculations, or processing, for a computer. Also called a processor or central processing unit (CPU).",
        "mobile device": "A hand-help device that uses wireless technologies.",
        "motherboard": "The central circuit board of a computer to which all other devices connect.",
        "multitasking": "Two or more programs (tasks) running simultaneously on a computer.",
        "New Technology File System (NTFS)": "An expandable file system used by the Windows OS. It uses transaction processing to track changes to files and includes many other features. The most important of these features are file and folder security and file encryption.",
        "operating system (OS)": "A collection of programs that provides a computer with critical functionality, such as the user interface, management of hardware and software, and ways of creating, managing, and using files.",
        "partition": "An area of a storage device where the logical structure of a single file system may reside.",
        "personal computer (PC)": "A computer running Windows or Linux.",
        "portable operating system": "An operating system that you can use on a variety of computer system platforms, with only minor alterations required to be compatible with the underlying architecture.",
        "processes": "Components of a program that are active in memory.",
        "random-access memory (RAM)": "Memory that acts as the main memory for holding active programs.",
        "screen rotation": "A feature of mobile operating systems that takes advantage of the built-in hardware accelerometer in a device by rotating the image on the screen to accommodate the device's position and allow you to read the screen.",
        "security": "An operating system function that provides password-protected authentication of the user before allowing access to the local computer. Security features may restrict what a user can do on a computer.",
        "server": "A computer that plays one or more of several important roles in a network. In all these roles, it provides services to other computers (clients).",
        "smartphone": "A device that works as a cell phone but also lets you connect to the Internet, view your email, and install a variety of apps for entertainment, education, and work.",
        "solid-state drive (SSD)": "A storage device that uses integrated circuits, which can be written to and read from much faster than conventional hard disk drives and optical drives.",
        "system firmware": "Program code that informs the processor of the devices present and how to communicate with them.",
        "system on a chip (SoC)": "The single microchip containing all or most of the electronic circuity required for a device.",
        "tablet": "A mobile device that has a touch screen, no integrated keyboard (usually), is larger than a smartphone, and is much more portable than a laptop computer.",
        "task management": "An operating system function in multitasking OSs that controls the focus. The user can switch between tasks by bringing an application to the foreground, which gives the focus to that application.",
        "user interface (UI)": "The software layer, sometimes called the shell, through which the user communicates with the OS, which, in turn, communicates with the computer hardware.",
        "virtual keyboard": "A screen image of a keyboard with labeled keys that you can tap to enter characters when required.",
    },
    # Chapter 3 terms
    "3": {
        "application virtualization": "A type of virtualization in which a user connects to a server and accesses one or more applications rather than an entire desktop environment.",
        "augmented reality (AR)": "viewing something in real time through a camera or other device while the image (or other input) is digitally modified.",
        "avatar": "An animated computer-generated human used in a virtual world to represent an individual.",
        "desktop virtualization": "The software virtualization of a desktop computer into which you can install an operating system.",
        "dumb terminal": "A device consisting of little more than a keyboard and display with a connection to a host computer (mainframe or minicomputer) and having no native processing power of its own (hence the term dumb).",
        "guest OS": "An operating system running within a virtual machine.",
        "host key": "A key combination used to release control of the keyboard and mouse from within a virtual machine so that they can be used in the host OS.",
        "host OS": "The operating system installed directly on a computer and into which a virtual machine is installed.",
        "hypervisor": "The software layer that emulates the necessary hardware on which an operating system runs, allowing multiple operating systems to run simultaneously on a single computer.",
        "ISO file": "an image of the contents of a CD or DVD.",
        "network virtualization": "a network addressing space that exists within one or more physical networks, but which is logically independent of the physical network structure.",
        "Second-Level Address Translation (SLAT)": "A feature found in many newer Intel and AMD CPUs and required by some hypervisors.",
        "server virtualization": "Virtualization in which a single machine hosts multiple virtual servers, each of which performs tasks as independently from the others as separate physical machines would.",
        "storage virtualization": "Virtualization of networked data storage in which client computers can utilize many networked hard drives as though they are one.",
        "terminal client": "Client software that enables a user to connect to server-based terminal services that provide an environment, called a partition, in which the user accesses programs on the server.",
        "terminal services": "A server-based service that creates individual environments, called partitions, within which a user can work in programs after remotely connecting over a network.",
        "thin client": "A low-cost PC, usually without such common peripherals as diskette drives (now gone from most PCs), expansion slots, and optical drives. The purpose of a thin client is to connect to a server, allowing the user to work in a server-hosted environment.",
        "Type I hypervisor": "A hypervisor that can run directly on a computer without an underlying host operating system.",
        "Type II hypervisor": "A hypervisor that requires a host operating system.",
        "Type II hypervisor": "A hypervisor that requires a host operating system.",
        "virtual machine (VM)": "A virtual environment that emulates a computer and supports the installation of an operating system.",
        "virtual reality (VR)": "A virtual environment that includes three-dimensional images and involves other senses, giving the participant a feeling of actually being present in that time and space.",
        "virtual world": "A computer-based environment inhabited by animated computer-generated human stand-ins (called avatars). An individual uses an avatar to represent themselves within the virtual world, interacting with other avatars.",
        "virtualization": "The creation of an environment that seems real but isn't.",
        "Windows XP Mode": "Windows Virtual PC with a free and legal Windows XP VM preinstalled. Only available in certain editions of Windows 7.",
    },
    # Chapter 5 terms
    "5": {
        "bloatware": " Slang for the software added to a computer when it is purchased with Windows preinstalled. Some of these programs are useful, but most of it is annoying or may be free trial software that you can try, but must purchase to use after the trial period expires.",
        "continuum": "A feature for working on a two-in-one device. With the keyboard attached, Windows 10 displays in PC-style Desktop mode. Detach the keyboard and the ____ feature automatically changes to Tablet mode on the fly.",
        "Cortana": "____ is an intelligent search system that searches the Web, your computer or device, and any cloud storage you use from that computer. You do not need to remember a syntax with Cortana, instead you can ask questions as if you are talking with a person. Cortana also learns about you, not by spying but by paying attention to things you give her permission to watch, using the Notebook feature.",
        "desktop mode": "Windows 10 ____ ____ displays the Start menu covering a portion, but not all, of the Desktop.",
        "device manager": "A Control Panel applet that displays the list of hardware and the status of each device.",
        "domain joined": "A feature that allows a Windows computer to join a Microsoft Active Directory Domain.",
        "Ease of Access": "A Windows feature for configuring audio and visual aids for those who need them.",
        "FIDO Alliance": "An industry consortium in which the members, representing industries such as banking, software, hardware, and more can contribute their technology and work together to develop solutions to allow users to securely access online services and conduct financial transactions without using password authentication to reduce the risk of fraud. FIDO is an acronym for Fast Identity Online.",
        "File Explorer": "The Windows file management tool in Windows 8.1 and Windows 10, previously named Windows Explorer.",
        "Hey Cortana": "A voice activation option that was introduced in Windows Phone 8.1 and made available to Windows 10 for those devices that support voice input. It takes some training of the app by the user to ensure that Cortana responds to the voice query.",
        "keyboard shortcut": "A key combination that performs an assigned action, saving you several mouse or keyboard actions.",
        "live tile": "A rectangular object on the Windows 8.1 Start screen and the Windows 10 Start menu that, when tapped with a finger or clicked with a mouse, launches an app. The “live” part of the name is due to a tile's ability to display active content related to the app without requiring you to launch the app.",
        "lock screen": "A screen that displays after Windows 8.1 start up. It also displays when Windows is locked or when a period of inactivity triggers the screen saver. You must use a swiping motion to close the Lock screen and access either the Sign-in screen or the Start screen.",
        "Microsoft Account (MSA)": "A free account with Microsoft that gives the subscriber access to Microsoft services, such as Outlook.com, Messenger, OneDrive, and Xbox Live.",
        "Microsoft Edge": "An alternative to the decades-old Internet Explorer (IE), which is also included in Windows 10 for backward compatibility with some websites.",
        "Microsoft Passport": "____ ____ lets you securely sign in to network resources without sending a password or PIN over the network; the authentication is tied to the hardware.",
        "multitouch": "The ability to interpret multiple simultaneous touch gestures, such as the pinching gesture in which fingers first touch the device (screen, touch mouse, or touch pad) at separate locations and then pinch together while in contact with the device.",
        "Out of Box Experience (OOBE)": "A feature on a new computer with Windows 8.1 or Windows 10 preinstalled. When you take it out of the box and turn it on, you will be greeted with this last phase of Windows installation where you personalize the GUI and configure how you will sign in. Of course, it is also the last phase of a clean Windows installation.",
        "picture-in-picture (PIP)": "The Xbox app supports ____-____-____ ____ in which one show displays on the screen while another displays in a small box. This has been a feature of TVs for decades.",
        "predictive notification": "Providing a notice or other information in anticipation of a need.",
        "quick link": "What was called a shortcut on the Start menu in Windows 7 is now called a ____ ____.",
        "start button": "A graphical button on the far left of the task bar that opens the Start menu.",
        "tablet mode": "A mode in which all apps run full screen that is activated when Windows 10 wakes up on a tablet without an attached keyboard. The Start menu opens full screen (Tablet mode) to work better with a touch screen. Manually switch to Tablet mode using the Tablet mode button in the Action Center.[Action Center contains all notifications in one place, as well as convenient buttons to change settings.]",
        "task view": "Windows 10 ____ ____ lets you quickly view all your open apps and improves on the Windows 7 Aero Flip 3D feature. In addition, use ____ ____ to switch between Virtual Desktops.",
        "two-step verification": "A way to provide a second step beyond just using password authentication. It adds extra security. When you configure your Microsoft account with ____-____ ____, you provide a telephone number where you can receive text messages. When Microsoft uses ____-____ ____, it shows the last two digits of your phone number and you respond with the last four digits. Then the system texts you a numeric code on your phone which you then enter as a verification code.",
        "universal app": "A ____ ____ (type of app) conforms to different screen sizes and other features, such as input type (keyboard/mouse vs. touch screen) and makes the switch automatically.",
        "user tile": "A tile at the very top of the left pane of the Start menu for the currently signed-in user, with a picture, if the user chooses to add one.",
        "Virtual Desktop": "A ____ ____ allows you to group your projects into multiple desktops. For instance, on a home PC you could create a personal finance Desktop with windows for Quicken, Excel, a calculator app, and your personal banking website open in one ____ ____. [The generic term for Virtual Desktops is “workspaces.”]",
        "Web-based setup": "An online Windows setup, available through the Microsoft website for upgrading to Windows 10.",
        "Web Note": "A tool that lets you mark up and save a Web page by allowing you to write or draw on the page, highlight items, erase your annotations, clip a portion of a page, and save the Web page with your annotations. You can then share it with other people.",
        "Windows 10 Home Edition": "____ ____ ____ ____ runs on PCs and tablets and is aimed at consumers who do not need some of the premium features of Windows 10 Pro.",
        "Windows 10 Pro": "____ ____ ____ runs on PCs and tablets. It is equivalent to the Windows 8.x Pro, Windows 7 Professional, and Windows 7 Ultimate operating systems that offer features required for business.",
        "Windows Hello": "A new biometric sign-in feature that lets you sign in to your Windows 10 device with a biometric sign-in such as fingerprint, facial recognition, or iris scan. It requires the existence of special hardware in the Windows 10 computer.",
        "Windows key": "A key located near the bottom left of most keyboards with a Windows logo on it. It is used alone and in combination with other keys as keyboard shortcuts.",
        "Windows Setup": "The traditional program for installing and upgrading Windows. It is run from disc or from the source files.",
        "Xbox Game bar": "If you have an Xbox One, Windows 10 lets you access your Xbox data such as friends, activity, game history, and record video game clips. The Xbox Game bar contains buttons that let you record games, take screenshots of games, and configure Xbox.",
    },
    # Chapter 6 terms
    "6": {
        "binary file": "A file that contains program code, as opposed to a file containing data.",
        "bootloader": "The Windows OS startup code that gets loaded in memory.",
        "bootstrap loader": "A firmware program that uses hardware configuration settings stored in nonvolatile memory (commonly called CMOS) to determine what devices can start an OS and the order in which the system will search these devices while attempting to begin the OS startup process.",
        "code signing": "A practice introduced in Windows 2000 in which all of the operating system code is digitally signed to show that it has not been tampered with.",
        "Command Prompt": "A command-line interface (CLI) that you can launch from within Windows, from Safe Mode, or as a Recovery option.",
        "Consent Prompt": "A prompt requesting permission from an administrator to proceed with an action that requires administrator privileges.",
        "Credentials Prompt": "A prompt requesting that a standard user provide computer administrator credentials before granting permission to proceed with an action that requires administrator privileges.",
        "data type": "A special data format in the Windows registry. There are several registry data types, such as REG_BINARY, REG_DWORD, and so forth.",
        "Device Stage": "A Windows 7 feature which, if the device supports it, will bring up a page from which you can make many choices for managing the device, and it often includes an accurate image of the device.",
        "digital signature": "In Windows, encrypted data that can be unencrypted by Windows in a process called file signature verification.",
        "driver signing": "Code signing of device drivers that indicates two things: the integrity of the file or files, and that the device driver has passed Microsoft's tests for compatibility.",
        "Early Launch Anti-Malware (ELAM)": "A security component that examines each of the device drivers before they load into memory, thus preventing suspicious drivers from loading.",
        "Fast Boot": "A start-up feature that takes advantage of the hibernated kernel of the Windows 8 Hybrid Shutdown by bring the hibernated system session out of hibernation, saving all the work of the Kernel Loading phase.",
        "file signature verification": "The process by which Windows unencrypts a digital signature and verifies that the file has not been tampered with in any way.",
        "Hibernate": "The process of saving to disk an image of the contents of RAM, including the OS, open apps, and all the associated data before the OS sends the command to power down the computer.",
        "hive": "The portion of the Windows registry represented in one registry file.",
        "Hybrid Shutdown": "In Windows 8, when you select Shutdown from the Power menu it 1) sends messages to all running apps to save data and settings and then it shuts down the apps, 2) closes the session for each logged-on user, and 3) hibernates the Windows session and saves it in a file.",
        "key": "In the Windows registry, a folder object that may contain one or more sets of settings as well as other keys.",
        "Last Known Good Configuration": "A startup option that starts Windows normally and selects the configuration that existed at the last successful user logon, ignoring changes made after the last logon.",
        "logon phase": "The phase of startup that includes authenticating the user, starting the Windows Logon service, runs existing logon scripts during program startup, and starts plug-and-play detection.	",
        "Measured Boot": "A UEFI firmware feature that logs the start-up process so antimalware software can analyze this log to determine if malware is on the computer or if the boot components were tampered with.",
        "MSCONFIG": "The System Configuration Utility, a Windows tool for modifying system start-up, allows you to modify and test start-up configuration settings without having to alter the settings directly. It allows you access to settings buried within the registry and allows you to make the changes temporary or permanent.",
        "plug and play": "The ability of a computer to automatically detect and configure a hardware device. To work, the computer, the device, and the OS must all comply with the same ____ ____ ____ standard.",
        "power-on self-test (POST)": "A series of firmware program tests of the system hardware that determines the amount of memory present and verifies that devices required for OS startup are working.",
        "registry": "A database of all configuration settings in Windows.",
        "root key": "In the Windows registry, the top five folders are ____ ___s, often called subtrees in Microsoft documentation. Each of these subtrees is the top of a hierarchical structure containing folders called keys.",
        "Safe Mode": "A mode for starting Windows with certain drivers and components disabled.",
        "Safe Mode with Command Prompt": "A mode for starting Windows with only a command prompt as a user interface.",
        "Secure Boot": "The UEFI firmware feature that loads only trusted operating system bootloaders.",
        "security ID (SID)": "A unique string of numbers preceded by S-1-5 that identifies a security principal in a Windows security accounts database.",
        "Sleep": "The ____ power option causes the computer to stay on in a very-low-power mode; the system state and user session (applications and data) are saved in RAM, but the screen turns off.",
        "subkey": "In the Windows registry, a key that exists within another key.",
        "System Recovery Command Prompt": "An advanced command-line interface where you can enter commands to repair Windows.",
        "Trusted Boot": "A Windows 8 feature that examines each of the system files required for the boot process before it loads into memory.",
        "Unified Extensible firmware Interface (UEFI)": "A standard for system firmware in modern computers that replaced the decades old ROM-BIO.",
        "value entry": "A setting within a Windows registry key.",
        "warm boot": "A restart of the firmware and operating system without a power down and power up cycle.",
        "Windows PowerShell": "A command-line interface (CLI) that accepts text input and accepts objects, as defined by object-oriented programming.",
        "Windows Recovery Environment (Windows RE)": "A component of Windows PE that, when needed, provides support with a powerful group of diagnostic and repair tools. ",
    },
    "m": {  # cti120 midterm
        "algorithm": "An ____ is a predetermined arrangement of well-defined instructions, usually to perform a computation or solve a class of problems",
        "backbone": "Another term for bus, the primary cable that connects all nodes",
        "broadcast": "A Packet is forwarded to all the hosts connected to the network",
        "broadcast domain": "A ____ ____ represents the domain or area in which all connected nodes receive a broadcast packet",
        "collision domain": "A ____ ____ represents the domain or area in which all connected nodes may experience a data collision",
        "dense": "The number of connections considering the number of possible connections",
        "distributed": "A ____ network is a type of computer network that is spread over different networks",
        "frame": "An Ethernet ____ can be thought of as a container for data with a source and destination address to deliver information, called the payload",
        "hardware": "Computer ____ is the physical components that a computer system requires to function",
        "host": "A ____ is a computer, typically a client or server on a network",
        "hub": "____ is a network hardware device used to connect multiple Ethernet devices that communicate in half-duplex mode",
        "IP": "the communications protocol that offers a location and identification for computers on networks and routes traffic across the Internet.",
        "IP address": "A logical address assigned to each host on a network",
        "media access control (MAC) address": "____ ____ ____ (____) ____ is the physical address of a network node",
        "network interface card (NIC)": "A Hardware component installed on your device so that it can connect to the Internet",
        "Network redundancy": "In the event of a failure a network will remain functioning due to additional devices or communication links",
        "node": "A ____ is any active, physical, electronic device attached to a network.",
        "open systems interconnection (OSI)": "A Conceptual model that characterizes and standardizes the communication functions of a network",
        "protocol": "A Network ____ is an established set of rules that determine how data is transmitted between different devices in the same network",
        "radio frequency (RF)": "A ____ ____ (____) signal refers to a wireless electromagnetic signal used as a form of communication",
        "scale": "To grow and manage increased demand",
        "segment": "In networking ____ means to separate",
        "switch": "____ is a network hardware device used to connect multiple Ethernet devices that communicate in full-duplex mode",
        "transmission media": "____ ____ is a pathway that carries the information from sender to receiver",
        "VLAN": "____ ____ ____ ____ A ____ is a logical grouping of devices/ports in the same broadcast domain",
        "conceptual model": "A ____ ____ illustrates a system to help people understand a topic or concept",
        "fragmentation": "____ is when a datagram is divided into fragments at the network layer once received from the transport layer because its too large",
        "mnemonic": "A ____ is any learning system that assistances in retention or retrieval in the human memory",
        "attenuation": "____ refers to the loss or reduction of signal strength",
        "bands": "Wireless frequency ____ are frequency ranges that are selected to carry wireless signals",
        "network backbones": "____ ____ comprise core network devices and are used to connect WANs or LANs",
        "omnidirectional": "____ means to broadcast in all directions",
        "Xerox Alto": "The ____ ____ is recognized as the first computer to use an Operating System (OS) with a graphical user interface",
        "alphanumeric": "________ are designed using alphabetical and numerical characters",
        "Network Address Translation (NAT)": "____ ____ ____ (____) translates a private address to a public address",
        "octet": "an ____ when referring to networks identifies 8 bits",
        "bottleneck": "A network ____ refers to a discrete condition in which data flow is limited by network resources and tends to cause the network to slow down",
        "fully qualified domain name (FQDN)": "A ____ ____ ____ ____ (____) is one that contains both a hostname and a complete domain name.",
        "routing protocol": "A ____ ____ defines the set of rules used by a router when it communicates routing information between adjacent routers.",
    },
    "dm": {  # dba120 midterm
        "American National Standards Institute (ANSI)": "One of two industry-accepted committees that sets standards for SQL.",
        "Entity-Relationship (E-R) Model": "A diagram that identifies the entities and data relationships in a database. The model is a logical representation of the physical system to be built.",
        "NULL value": "Means no value has been stored in that particular field. A ____ ____ indicates the absence of data, not a blank space.",
        "SQL*Plus": "A tool enabling users to interact with the database. Through ____, users can enter SQL commands, set or alter environmental variables, display the structure of tables, and execute interactive scripts.",
        "application cluster environment": "A high-volume work environment in which multiple users simultaneously request data from a database.",
        "bridging table": "A table created to eliminate a many-to-many relationship between two tables.",
        "character": "The basic unit of data. It can be a letter, number, or special symbol.",
        "character field": "A field composed of nonnumeric data. This field will not display a heading longer than the width of the data stored in the field.",
        "child table": 'A table having data that reference data within a parent table. Considered the "many" side in a one-to-many relationship.',
        "clause": "Each section of a statement that begins with a keyword (SELECT ____, FROM ____, WHERE ____, etc.).",
        "column": 'In a relational database, fields are commonly represented as columns and may be referred to as "columns."',
        "column alias": "Another name substituted for a column name. A ____ ____ is created in a query and displayed in the results.",
        "common column": "A column that exists in two or more tables and contains equivalent data.",
        "common field": 'A column that exists in two tables and is used to "join" two tables.',
        "comparison operator": "A search condition that indicates how data should relate to a given search value (equal to, greater than, less than, etc.). Common ____ ____s include >, <, >=, and <= .",
        "concatenation": "The combining the contents of two or more columns or character strings. Two vertical bars, or pipes (||), instruct Oracle 12c to ____ the output of a query.",
        "condition": "A portion of an SQL statement that identifies what must exist, or a requirement that must be met. When a query is executed, any record meeting the given ____ will be returned in query results.",
        "constraints": "Rules that ensure the accuracy and integrity of data. ____ prevent data that violate these rules from being added to tables. ____ include PRIMARY KEY, FOREIGN KEY, UNIQUE, CHECK, NOT NULL.",
        "data definition language (DDL)": "Commands, basically SQL commands, that create or modify database tables or other objects.",
        "data dictionary": 'Oracle 12c stores all information about database objects in this "dictionary." Stored information includes objects\' names, types, structures, owners, and the identity of users who have access to each object.',
        "data manipulation language (DML)": "Commands used to modify data. Changes to data made by DML commands are not accessible to other users until the data is committed.",
        "data redundancy": "Refers to having the same data in different places within a database, which wastes spaces and complicates database updates and changes.",
        "database": "A collection of interrelated files.",
        "database management system (DBMS)": "A generic term that applies to a software product that allows users to interact with a database to create and maintain the structure of the database, and then to enter, manipulate, and retrieve the data it stores.",
        "database object": "A defined, self-contained structure in Oracle 12c. ____ ____ include tables, sequences, indexes, and synonyms.",
        "datatype": "Identifies the type of data Oracle9i will be expected to store in a column.",
        "dynamic view": "Used to access statistics relating to the database's performance. See view.",
        "entity": "Any person, place, or thing with characteristics or attributes that will be included in a database. In the E-R model, an ____ is usually represented as a square or rectangle.",
        "equality operator": "A search condition that evaluates data for exact, or equal, values. The ____ ____ symbol is the equal sign (=).",
        "exclusive lock": "When DDL operations are performed, Oracle 12c places this lock on a table so that no other user can alter the table or place a lock on it. See table locks.",
        "field": "One attribute or characteristic of a database entity.",
        "file": "A group of records about the same type of entity.",
        "first-normal form (1NF)": "The first step in the normalization process in which repeating groups of data are removed from database records.",
        "foreign key": "When a common column exists in two tables, it will usually be a primary key in one table and will be called a ____ ____ in the second table.",
        "function-based index": "Can be used when a query is based on a calculated value or a function. See index.",
        "index": "A separate database object that stores frequently referenced values so they can be quickly located. An ____ can either be created implicitly by Oracle 12c or explicitly by a user.",
        "keywords": "Words used in a SQL query that have a predefined meaning to Oracle9i. Common ____ include SELECT, FROM, and WHERE.",
        "locks": 'When DML commands are issued, Oracle 12c implicitly "____" the row or rows being affected so that no other user can change the same data.',
        "logical operators": "Used to combine two or more search conditions. The ____ ____ include AND and OR. The NOT operator reverses the meaning of search conditions.",
        "lookup table": "A table referenced by a foreign key constraint",
        "normalization": "A multistep process that allows designers to take the raw data about an entity and evolve the data into a form that will reduce a database's data redundancy.",
        "numeric column": "A column composed of only numeric data. In output, the column will display the entire column heading, regardless of the width of the field. (Also known as a numeric field.)",
        "primary key": "A field that serves to uniquely identify a record in a database table.",
        "primary sort": "When only one column is specified in the ORDER BY clause, data is ordered, or sorted, based on the data organization within the specified column.",
        "private synonym": "An alias used by an individual to reference objects owned by that individual. See synonym.",
        "projection": "Choosing specific column(s) in a SELECT statement.",
        "public synonym": "An alias that can be used by others to access an individual's database objects. See synonym.",
        "query": "A question posed to the database.",
        "record": "A collection of fields describing the attributes of one database element. In PL/SQL, a ____ is a composite datatype that can assume the same structure as the row being retrieved.",
        "referential integrity": "When a user refers to something that exists in another table, the REFERENCES keyword is used to identify the table and column that must already contain the data being entered.",
        "relational database management system (RDBMS)": "A software program used to create a relational database. It has functions that allow users to enter, manipulate, and retrieve data.",
        "row": "A group of column values for a specific occurrence of an entity. In a database, records are commonly represented as rows.",
        "schema": "A collection of database objects owned by one user. By grouping objects according to the owner, multiple objects can exist in the same database that have the same object name.",
        "second-normal form (2NF)": "The second step in the normalization process in which partial dependencies are removed from database records.",
        "secondary sort": "When two or more columns are specified in the ORDER BY clause, data in the second column (or additional columns) provide an alternative field on which to order data if an exact match occurs between two or more rows in the first, or primary, sort.",
        "sequence": "A database object that generates sequential integers that can be used for an organization's internal controls. A ____ can also serve as a primary key for a table.",
        "shared lock": "A table lock that lets other users access portions of a table but not alter the structure of table. See table locks.",
        "string literal": 'Alphanumeric data, enclosed within single quotation marks, that instructs the software to interpret "literally" exactly what has been entered and to show it in the resulting display.',
        "structured query language (SQL)": "The industry standard for interacting with a relational database. It is a data sublanguage, and unlike a programming language, it processes sets of data as groups and can navigate data stored within various tables.",
        "substitution variable": "Instructs Oracle 12c to use a substituted value in place of a specific variable at the time a command is executed. Used to make SQL statements or PL/SQL blocks interactive.table",
        "synonym": "An alternative name given to a database object with a complex name. A ____ can be either private or public.",
        "syntax": "The basic structure, pattern, or rules, for an SQL statement. For an SQL statement to execute properly, the correct ____ must be used.",
        "third-normal form (3NF)": "The third step in the normalization process in which transitive dependencies are removed from database records.",
        "transaction": "A series of DML statements is considered to be one ____. In Oracle 12c, a ____ is simply a series of statements that have been issued and not committed. The duration of a transaction is defined by when a COMMIT implicitly or explicitly occurs.",
        "transaction control": "Data control statements that either save modified data or undo uncommitted changes made in er",
        "unnormalized": "Refers to database records that contain repeating groups of data (multiple entries for a single column).",
        "virtual column": "A column value that is automatically generated based on the expression used to define the column.",
        "wildcard characters": "Symbols used to represent one or more alphanumeric characters. The ____ ____ in Oracle 12c are the percent sign (%) and the underscore symbol ( _ ). The percent sign is used to represent any number of characters; the underscore represents one character.",
    },
}
